from __future__ import annotations

import logging
from typing import TypedDict

from langgraph.graph import END, START, StateGraph

from app.features.production_planning.cpsat_model_builder import (
    CpsatModelBundle,
    build_base_cpsat_model,
)
from app.features.production_planning.objectives import apply_objective_by_variant
from app.features.production_planning.plan_comparator import compare_plans
from app.features.production_planning.preprocessing import normalize_request
from app.features.production_planning.schemas import (
    PLAN_VARIANTS,
    NormalizedPlanningData,
    PlanComparisonSummary,
    PlanResult,
    ProductionPlanningRequest,
    ProductionPlanningResult,
)
from app.features.production_planning.solution_extractor import extract_plan_result
from app.features.production_planning.solver import solve_model
from app.features.production_planning.validators import validate_request

logger = logging.getLogger(__name__)


class ProductionPlanningGraphState(TypedDict, total=False):
    request: ProductionPlanningRequest
    validated_request: ProductionPlanningRequest
    normalized_data: NormalizedPlanningData
    plan_results: list[PlanResult]
    comparison_summary: PlanComparisonSummary
    result: ProductionPlanningResult


def build_production_planning_graph():
    """
    Parameters:
        - None.

    Methodology:
        - Build a LangGraph StateGraph that validates, normalizes, generates all six plan
          variants, compares them, and finalizes a single response.

    Output:
        - A compiled LangGraph workflow that accepts ProductionPlanningGraphState.
    """
    graph = StateGraph(ProductionPlanningGraphState)
    graph.add_node("validate_request", validate_request_node)
    graph.add_node("normalize_request", normalize_request_node)
    graph.add_node("generate_plan_variants", generate_plan_variants_node)
    graph.add_node("compare_plan_variants", compare_plan_variants_node)
    graph.add_node("finalize_result", finalize_result_node)

    graph.add_edge(START, "validate_request")
    graph.add_edge("validate_request", "normalize_request")
    graph.add_edge("normalize_request", "generate_plan_variants")
    graph.add_edge("generate_plan_variants", "compare_plan_variants")
    graph.add_edge("compare_plan_variants", "finalize_result")
    graph.add_edge("finalize_result", END)
    return graph.compile()


def run_production_planning_graph(
    request: ProductionPlanningRequest,
) -> ProductionPlanningResult:
    """
    Parameters:
        - request: Production planning request to execute through the LangGraph workflow.

    Methodology:
        - Invoke the compiled graph with the request as initial state.
        - Read the final ProductionPlanningResult from the terminal graph state.

    Output:
        - ProductionPlanningResult generated by connected LangGraph nodes.
    """
    state = build_production_planning_graph().invoke({"request": request})
    return state["result"]


def validate_request_node(
    state: ProductionPlanningGraphState,
) -> dict[str, ProductionPlanningRequest]:
    """
    Parameters:
        - state: LangGraph state containing the original planning request.

    Methodology:
        - Run domain validation before any model construction.
        - Store the validated request for downstream nodes.

    Output:
        - Partial graph state with validated_request.
    """
    request = state["request"]
    logger.info("production_planning.validation.started")
    validated = validate_request(request)
    logger.info("production_planning.validation.completed", extra={"orders": len(validated.orders)})
    return {"validated_request": validated}


def normalize_request_node(
    state: ProductionPlanningGraphState,
) -> dict[str, NormalizedPlanningData]:
    """
    Parameters:
        - state: LangGraph state containing a validated request.

    Methodology:
        - Convert datetimes and business inputs into integer CP-SAT-ready data.
        - Share normalized data with all objective variants.

    Output:
        - Partial graph state with normalized_data.
    """
    validated = state["validated_request"]
    logger.info("production_planning.preprocessing.started")
    normalized = normalize_request(validated)
    logger.info(
        "production_planning.preprocessing.completed",
        extra={"orders": len(normalized.orders), "lines": len(normalized.lines)},
    )
    return {"normalized_data": normalized}


def generate_plan_variants_node(
    state: ProductionPlanningGraphState,
) -> dict[str, list[PlanResult]]:
    """
    Parameters:
        - state: LangGraph state with validated_request and normalized_data.

    Methodology:
        - For each plan variant, build a fresh CP-SAT model, apply the variant objective,
          solve, and extract results.

    Output:
        - Partial graph state with plan_results.
    """
    validated = state["validated_request"]
    normalized = state["normalized_data"]
    plan_results = []

    for variant_code in PLAN_VARIANTS:
        bundle = _build_objective_bundle(normalized, validated, variant_code)
        apply_objective_by_variant(
            bundle.model,
            bundle,
            normalized,
            validated.solver_config,
            variant_code,
        )
        plan_results.append(_solve_extract_plan(bundle, normalized, validated, variant_code))

    return {"plan_results": plan_results}


def compare_plan_variants_node(
    state: ProductionPlanningGraphState,
) -> dict[str, PlanComparisonSummary]:
    """
    Parameters:
        - state: LangGraph state containing all solved plan variants.

    Methodology:
        - Compare all plan variants with the ranking and recommendation policy.

    Output:
        - Partial graph state with comparison_summary.
    """
    return {"comparison_summary": compare_plans(state["plan_results"])}


def finalize_result_node(
    state: ProductionPlanningGraphState,
) -> dict[str, ProductionPlanningResult]:
    """
    Parameters:
        - state: LangGraph state containing plan results and comparison summary.

    Methodology:
        - Assemble the final response model and collect warnings and solver metadata by variant.

    Output:
        - Partial graph state with result.
    """
    plan_results = state["plan_results"]
    comparison_summary = state["comparison_summary"]
    warnings = []
    for plan in plan_results:
        warnings.extend(plan.warnings)

    return {
        "result": ProductionPlanningResult(
            status="COMPLETED",
            plan_results=plan_results,
            recommended_plan_variant_code=comparison_summary.recommended_plan_variant_code,
            comparison_summary=comparison_summary,
            warnings=warnings,
            solver_metadata={
                plan.plan_variant_code: plan.solver_metadata for plan in plan_results
            },
        )
    }


def _build_objective_bundle(
    normalized: NormalizedPlanningData,
    validated: ProductionPlanningRequest,
    variant_code: str,
) -> CpsatModelBundle:
    logger.info("production_planning.model_build.started", extra={"variant_code": variant_code})
    bundle = build_base_cpsat_model(normalized, validated.solver_config)
    logger.info(
        "production_planning.model_build.completed",
        extra={
            "variant_code": variant_code,
            "orders": len(normalized.orders),
            "lines": len(normalized.lines),
            "optional_intervals": bundle.metric_vars["optional_interval_count"],
            "changeover_constraints": bundle.metric_vars["changeover_constraint_count"],
        },
    )
    return bundle


def _solve_extract_plan(
    bundle: CpsatModelBundle,
    normalized: NormalizedPlanningData,
    validated: ProductionPlanningRequest,
    variant_code: str,
) -> PlanResult:
    logger.info("production_planning.solver.started", extra={"variant_code": variant_code})
    raw = solve_model(bundle, variant_code, validated.solver_config)
    logger.info(
        "production_planning.solver.completed",
        extra={
            "variant_code": variant_code,
            "status": raw.status,
            "objective_value": raw.objective_value,
            "wall_time_seconds": raw.wall_time_seconds,
        },
    )
    plan = extract_plan_result(raw, bundle, variant_code, normalized)
    logger.info(
        "production_planning.extraction.completed",
        extra={
            "variant_code": variant_code,
            "scheduled": plan.metrics.scheduled_count,
            "unscheduled": plan.metrics.unscheduled_count,
            "delayed": plan.metrics.delayed_order_count,
        },
    )
    return plan
