from dataclasses import dataclass

from app.features.chat.access_control import (
    EXECUTIVE_ROLE,
    MANUFACTURING_MANAGER_ROLE,
    OPERATOR_ROLE,
    ROLE_INTENT_MATRIX,
)
from app.features.chat.schemas import ChatIntent

BUSINESS_ALLOWED_ROLES = frozenset(
    {
        OPERATOR_ROLE,
        EXECUTIVE_ROLE,
        MANUFACTURING_MANAGER_ROLE,
    }
)
MANAGER_ALLOWED_ROLES = frozenset(
    {
        EXECUTIVE_ROLE,
        MANUFACTURING_MANAGER_ROLE,
    }
)


@dataclass(frozen=True)
class RdbEvidenceViewDefinition:
    intent: ChatIntent
    view_name: str
    source_type: str
    source: str
    reference_id_column: str
    title_columns: tuple[str, ...]
    summary_columns: tuple[str, ...]
    data_columns: tuple[str, ...]
    allowed_roles: frozenset[str]
    target_code_columns: tuple[str, ...] = ()
    date_filter_columns: tuple[str, ...] = ()
    restricted_columns: tuple[str, ...] = ()
    default_order_columns: tuple[str, ...] = ()
    schema_name: str = "chat_evidence"


RDB_EVIDENCE_VIEW_DEFINITIONS = (
    RdbEvidenceViewDefinition(
        intent=ChatIntent.MATERIAL_SHORTAGE,
        view_name="chat_material_shortage_evidence_view",
        source_type="MATERIAL",
        source="chat_material_shortage_evidence_view",
        reference_id_column="plan_material_id",
        title_columns=("material_code", "material_name", "material_plan_status"),
        summary_columns=(
            "plan_id",
            "order_no",
            "product_code",
            "product_name",
            "line_code",
            "material_code",
            "material_name",
            "required_quantity",
            "reserved_quantity",
            "shortage_quantity",
            "unit",
            "available_quantity",
            "safety_stock_quantity",
            "inventory_status",
            "expected_inbound_at",
            "expected_inbound_quantity",
        ),
        data_columns=(
            "plan_material_id",
            "plan_id",
            "order_id",
            "order_no",
            "product_id",
            "product_code",
            "product_name",
            "line_id",
            "line_code",
            "line_name",
            "material_id",
            "material_code",
            "material_name",
            "material_type",
            "required_quantity",
            "reserved_quantity",
            "consumed_quantity",
            "shortage_quantity",
            "unit",
            "material_plan_status",
            "current_quantity",
            "available_quantity",
            "inventory_reserved_quantity",
            "safety_stock_quantity",
            "expected_inbound_at",
            "expected_inbound_quantity",
            "inventory_status",
            "planned_start_at",
            "planned_end_at",
            "plan_status",
        ),
        allowed_roles=BUSINESS_ALLOWED_ROLES,
        target_code_columns=("material_code", "line_code", "order_no", "product_code"),
        date_filter_columns=("planned_start_at",),
        default_order_columns=("shortage_quantity", "planned_start_at", "plan_id"),
    ),
    RdbEvidenceViewDefinition(
        intent=ChatIntent.DELIVERY_RISK,
        view_name="chat_delivery_risk_evidence_view",
        source_type="PREDICTION",
        source="chat_delivery_risk_evidence_view",
        reference_id_column="prediction_id",
        title_columns=("order_no", "risk_level", "main_cause_type"),
        summary_columns=(
            "prediction_id",
            "order_no",
            "customer_name",
            "product_code",
            "product_name",
            "line_code",
            "due_date",
            "delay_probability",
            "risk_level",
            "predicted_delay_days",
            "main_cause_type",
            "cause_detail",
            "analysis_summary",
            "recommended_action",
            "predicted_at",
        ),
        data_columns=(
            "prediction_id",
            "order_id",
            "order_no",
            "product_id",
            "product_code",
            "product_name",
            "line_id",
            "line_code",
            "line_name",
            "plan_id",
            "due_date",
            "order_status",
            "delay_probability",
            "risk_level",
            "predicted_delay_days",
            "main_cause_type",
            "cause_detail",
            "analysis_summary",
            "recommended_action",
            "is_notified",
            "is_checked",
            "predicted_at",
        ),
        allowed_roles=BUSINESS_ALLOWED_ROLES,
        target_code_columns=("order_no", "line_code", "product_code"),
        date_filter_columns=("due_date",),
        restricted_columns=("contract_amount", "late_penalty_amount"),
        default_order_columns=("risk_level", "delay_probability", "predicted_at"),
    ),
    RdbEvidenceViewDefinition(
        intent=ChatIntent.PRODUCTION_PLAN,
        view_name="chat_production_plan_evidence_view",
        source_type="PLAN",
        source="chat_production_plan_evidence_view",
        reference_id_column="plan_id",
        title_columns=("plan_id", "line_code", "product_code", "plan_status"),
        summary_columns=(
            "plan_id",
            "order_no",
            "product_code",
            "product_name",
            "line_code",
            "line_name",
            "planned_start_at",
            "planned_end_at",
            "estimated_duration_hr",
            "planned_quantity",
            "plan_sequence",
            "plan_status",
        ),
        data_columns=(
            "plan_id",
            "order_id",
            "order_no",
            "product_id",
            "product_code",
            "product_name",
            "product_category",
            "line_id",
            "line_code",
            "line_name",
            "line_type",
            "operator_id",
            "operator_name",
            "planned_start_at",
            "planned_end_at",
            "estimated_duration_hr",
            "planned_quantity",
            "plan_sequence",
            "plan_status",
            "due_date",
            "order_quantity",
            "order_status",
        ),
        allowed_roles=BUSINESS_ALLOWED_ROLES,
        target_code_columns=("order_no", "line_code", "product_code"),
        date_filter_columns=("planned_start_at",),
        restricted_columns=("contract_amount", "late_penalty_amount"),
        default_order_columns=("planned_start_at", "plan_sequence", "plan_id"),
    ),
    RdbEvidenceViewDefinition(
        intent=ChatIntent.LINE_BOTTLENECK,
        view_name="chat_line_bottleneck_evidence_view",
        source_type="LINE",
        source="chat_line_bottleneck_evidence_view",
        reference_id_column="line_status_id",
        title_columns=("line_code", "operation_status", "recorded_at"),
        summary_columns=(
            "line_status_id",
            "line_code",
            "line_name",
            "operation_status",
            "throughput_rate",
            "current_yield_rate",
            "waiting_quantity",
            "waiting_time_hr",
            "utilization_rate",
            "progress_rate",
            "processed_quantity",
            "defect_quantity",
            "recorded_at",
            "abnormal_machine_count",
        ),
        data_columns=(
            "line_status_id",
            "line_id",
            "line_code",
            "line_name",
            "line_type",
            "product_id",
            "product_code",
            "product_name",
            "plan_id",
            "operator_id",
            "operator_name",
            "recorded_at",
            "operation_status",
            "throughput_rate",
            "current_yield_rate",
            "waiting_quantity",
            "waiting_time_hr",
            "processed_quantity",
            "defect_quantity",
            "utilization_rate",
            "progress_rate",
            "abnormal_machine_count",
            "abnormal_machine_codes",
            "latest_machine_status_note",
        ),
        allowed_roles=BUSINESS_ALLOWED_ROLES,
        target_code_columns=("line_code", "product_code"),
        date_filter_columns=("recorded_at",),
        default_order_columns=("waiting_time_hr", "waiting_quantity", "recorded_at"),
    ),
    RdbEvidenceViewDefinition(
        intent=ChatIntent.URGENT_ORDER_IMPACT,
        view_name="chat_urgent_order_impact_evidence_view",
        source_type="ORDER",
        source="chat_urgent_order_impact_evidence_view",
        reference_id_column="simulation_detail_id",
        title_columns=("order_no", "simulation_name", "simulation_type"),
        summary_columns=(
            "simulation_id",
            "simulation_detail_id",
            "simulation_name",
            "simulation_type",
            "order_no",
            "product_code",
            "product_name",
            "before_line_code",
            "after_line_code",
            "before_start_at",
            "before_end_at",
            "after_start_at",
            "after_end_at",
            "expected_completion_date",
            "after_is_delayed",
            "delay_reduction_hr",
            "change_reason",
            "recommendation_grade",
        ),
        data_columns=(
            "simulation_id",
            "simulation_detail_id",
            "simulation_group_id",
            "simulation_name",
            "simulation_type",
            "prediction_id",
            "order_id",
            "order_no",
            "plan_id",
            "product_id",
            "product_code",
            "product_name",
            "before_line_id",
            "before_line_code",
            "after_line_id",
            "after_line_code",
            "before_sequence",
            "after_sequence",
            "before_start_at",
            "before_end_at",
            "after_start_at",
            "after_end_at",
            "expected_completion_date",
            "after_is_delayed",
            "before_quantity",
            "after_quantity",
            "change_reason",
            "action_result",
            "before_total_delay_hr",
            "after_total_delay_hr",
            "delay_reduction_hr",
            "recommendation_grade",
            "created_at",
        ),
        allowed_roles=MANAGER_ALLOWED_ROLES,
        target_code_columns=("order_no", "before_line_code", "after_line_code", "product_code"),
        date_filter_columns=("after_start_at",),
        restricted_columns=("cost_change_amount",),
        default_order_columns=("recommendation_grade", "delay_reduction_hr", "created_at"),
    ),
    RdbEvidenceViewDefinition(
        intent=ChatIntent.WORK_PRIORITY,
        view_name="chat_work_priority_evidence_view",
        source_type="PLAN",
        source="chat_work_priority_evidence_view",
        reference_id_column="plan_id",
        title_columns=("priority_rank", "plan_id", "order_no", "risk_level"),
        summary_columns=(
            "priority_rank",
            "plan_id",
            "order_no",
            "product_code",
            "product_name",
            "line_code",
            "planned_start_at",
            "planned_end_at",
            "due_date",
            "plan_status",
            "risk_level",
            "main_cause_type",
            "shortage_count",
            "line_waiting_time_hr",
            "recommended_action",
        ),
        data_columns=(
            "priority_rank",
            "plan_id",
            "order_id",
            "order_no",
            "product_id",
            "product_code",
            "product_name",
            "line_id",
            "line_code",
            "line_name",
            "operator_id",
            "operator_name",
            "planned_start_at",
            "planned_end_at",
            "planned_quantity",
            "plan_sequence",
            "plan_status",
            "due_date",
            "prediction_id",
            "risk_level",
            "delay_probability",
            "main_cause_type",
            "shortage_count",
            "line_waiting_time_hr",
            "recommended_action",
        ),
        allowed_roles=BUSINESS_ALLOWED_ROLES,
        target_code_columns=("order_no", "line_code", "product_code"),
        date_filter_columns=("due_date",),
        restricted_columns=("contract_amount", "late_penalty_amount"),
        default_order_columns=("priority_rank", "due_date", "planned_start_at"),
    ),
    RdbEvidenceViewDefinition(
        intent=ChatIntent.REPORT_LOOKUP,
        view_name="chat_report_metadata_evidence_view",
        source_type="REPORT",
        source="chat_report_metadata_evidence_view",
        reference_id_column="report_id",
        title_columns=("report_title", "report_type"),
        summary_columns=(
            "report_id",
            "report_title",
            "report_type",
            "target_start_date",
            "target_end_date",
            "author_name",
            "included_items",
            "related_simulation_id",
            "created_at",
            "updated_at",
        ),
        data_columns=(
            "report_id",
            "report_title",
            "report_type",
            "author_id",
            "author_name",
            "target_start_date",
            "target_end_date",
            "included_items",
            "report_evidence",
            "related_simulation_id",
            "created_at",
            "updated_at",
        ),
        allowed_roles=BUSINESS_ALLOWED_ROLES,
        date_filter_columns=("created_at", "target_start_date", "target_end_date"),
        default_order_columns=("created_at", "report_id"),
    ),
)

RDB_EVIDENCE_VIEW_CATALOG = {
    definition.intent: definition
    for definition in RDB_EVIDENCE_VIEW_DEFINITIONS
}


def get_rdb_evidence_view_definition(
    intent: ChatIntent,
) -> RdbEvidenceViewDefinition | None:
    return RDB_EVIDENCE_VIEW_CATALOG.get(intent)


def get_allowed_rdb_evidence_intents(role: str) -> frozenset[ChatIntent]:
    normalized_role = role.strip().upper()
    role_intents = ROLE_INTENT_MATRIX.get(normalized_role, frozenset())
    return frozenset(
        intent
        for intent in role_intents
        if (
            definition := get_rdb_evidence_view_definition(intent)
        ) is not None
        and normalized_role in definition.allowed_roles
    )
